from enum import Enum

class NodeType(Enum):
    LET = "let"
    FCN_FORM = "fcn_form"
    IDENTIFIER = "identifier"
    INTEGER = "integer"
    STRING = "string"
    WHERE = "where"
    GAMMA = "gamma"
    LAMBDA = "lambda"
    TAU = "tau"
    REC = "rec"
    AUG = "aug"
    CONDITIONAL = "conditional"
    OP_OR = "op_or"
    OP_AND = "op_and"
    OP_NOT = "op_not"
    OP_COMPARE = "op_compare"
    OP_PLUS = "op_plus"
    OP_MINUS = "op_minus"
    OP_NEG = "op_neg"
    OP_MUL = "op_mul"
    OP_DIV = "op_div"
    OP_POW = "op_pow"
    AT = "at"
    TRUE_VALUE = "true_value"
    FALSE_VALUE = "false_value"
    NIL = "nil"
    DUMMY = "dummy"
    WITHIN = "within"
    AND = "and"
    EQUAL = "equal"
    COMMA = "comma"
    EMPTY_PARAMS = "empty_params"
    # Uncomment and add more if needed:
    # Y_STAR = "y_star"
    # LAMBDA_EXPRESSION = "lambda_expression"
    # BETA_OPERATOR = "beta_operator"
    # ENV_OPERATOR = "env_operator"
    # TUPLE = "tuple"
    # ETA_EXPRESSION = "eta_expression"
